---
- name: 安装Nginx
  hosts: all
  become: yes
  vars:
    target_port: 10080
    nginx_conf: "/etc/nginx/conf.d/default.conf"

  tasks:
    # 安装Nginx
    - name: 安装EPEL仓库
      yum:
        name: epel-release
        state: present

    - name: 安装Nginx
      yum:
        name: nginx
        state: present
      notify: 重启Nginx

    # 配置管理
    - name: 精确修改监听端口
      replace:
        path: "{{ nginx_conf }}"
        regexp: 'listen\s+80;'
        replace: 'listen {{ target_port }};'
        backup: yes
      notify: 重启Nginx

    # 验证配置
    - name: 检查配置语法
      command: nginx -t
      register: nginx_check
      changed_when: false
      failed_when: nginx_check.rc != 0

  handlers:
    - name: 重启Nginx
      service:
        name: nginx
        state: restarted