---
- name: CentOS 7 Nginx安装
  hosts: all
  become: yes
  vars:
    nginx_port: 10080
    nginx_version: "latest"

  tasks:
    - name: 确保防火墙已关闭
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: 安装基础依赖
      yum:
        name:
          - epel-release
          - yum-utils
        state: present
        update_cache: yes

    - name: 添加Nginx官方仓库
      yum_repository:
        name: nginx-stable
        description: Nginx Stable Repo
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: yes
        gpgkey: https://nginx.org/keys/nginx_signing.key
        enabled: yes

    - name: 安装Nginx
      yum:
        name: nginx
        state: "{{ nginx_version if nginx_version != 'latest' else 'present' }}"
        enablerepo: "nginx-stable,epel"
      notify:
        - 重启Nginx服务

    - name: 安全备份默认配置
      copy:
        src: /etc/nginx/conf.d/default.conf
        dest: /etc/nginx/conf.d/default.conf.bak
        remote_src: yes
      when: ansible_check_mode

    - name: 精确修改监听端口
      replace:
        path: /etc/nginx/conf.d/default.conf
        regexp: 'listen\s+80;'
        replace: 'listen {{ nginx_port }};'
        validate: '/usr/sbin/nginx -t -c %s'
      notify:
        - 重启Nginx服务

    - name: 验证服务状态
      uri:
        url: "http://localhost:{{ nginx_port }}"
        return_content: yes
      register: nginx_test
      until: nginx_test.status == 200
      retries: 5
      delay: 3

  handlers:
    - name: 重启Nginx服务
      service:
        name: nginx
        state: restarted
        enabled: yes