---
- name: CentOS 7 Nginx安装
  hosts: all
  become: yes
  vars:
    nginx_port: 10080  # 自定义端口号
    nginx_version: "latest"

  tasks:
    - name: 确保防火墙已关闭
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: 安装基础依赖
      yum:
        name:
          - epel-release
          - yum-utils
          - policycoreutils-python  # 用于SELinux管理
        state: present
        update_cache: yes

    - name: 添加Nginx官方仓库
      yum_repository:
        name: nginx-stable
        description: Nginx Stable Repo
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: yes
        gpgkey: https://nginx.org/keys/nginx_signing.key
        enabled: yes

    - name: 安装Nginx
      yum:
        name: nginx
        state: "{{ nginx_version if nginx_version != 'latest' else 'present' }}"
        enablerepo: "nginx-stable,epel"
      notify:
        - 重启Nginx服务

    - name: 修改监听端口为{{ nginx_port }}
      lineinfile:
        path: /etc/nginx/conf.d/default.conf
        regexp: '^    listen       80;'
        line: '    listen       {{ nginx_port }};'
        validate: 'nginx -t -c %s'  # 配置语法检查
      notify:
        - 重启Nginx服务

    - name: 验证服务状态
      uri:
        url: "http://localhost:{{ nginx_port }}"
        return_content: yes
      register: nginx_test
      until: nginx_test.status == 200
      retries: 5
      delay: 3

  handlers:
    - name: 重启Nginx服务
      service:
        name: nginx
        state: restarted
        enabled: yes