---
- name: CentOS 7 Nginx安全配置
  hosts: all
  become: yes
  vars:
    nginx_port: 10080
    nginx_conf: "/etc/nginx/conf.d/default.conf"

  tasks:
    - name: 确保防火墙已关闭
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: 安装基础依赖
      yum:
        name:
          - epel-release
          - yum-utils
        state: present
        update_cache: yes

    - name: 添加Nginx官方仓库
      yum_repository:
        name: nginx-stable
        description: Nginx Stable Repo
        baseurl: http://nginx.org/packages/centos/7/$basearch/
        gpgcheck: yes
        gpgkey: https://nginx.org/keys/nginx_signing.key
        enabled: yes

    - name: 安装Nginx
      yum:
        name: nginx
        state: present
        enablerepo: "nginx-stable,epel"
      notify:
        - 重启Nginx服务

    - name: 创建配置备份
      copy:
        src: "{{ nginx_conf }}"
        dest: "{{ nginx_conf }}.bak"
        remote_src: yes

    - name: 精确修改监听端口
      block:
        - name: 定位并修改监听端口
          replace:
            path: "{{ nginx_conf }}"
            regexp: '^(\s*listen\s+)80(;\s*#.*)?$'
            replace: '\1{{ nginx_port }}\2'
            validate: "/usr/sbin/nginx -t -c %s"

        - name: 验证配置有效性
          command: nginx -t
          register: nginx_check
          changed_when: false

        - name: 显示配置错误详情
          debug:
            var: nginx_check.stderr_lines
          when: nginx_check.rc != 0

      notify: 重启Nginx服务

    - name: 验证服务状态
      uri:
        url: "http://localhost:{{ nginx_port }}"
        return_content: yes
      register: nginx_test
      until: nginx_test.status == 200
      retries: 5
      delay: 3

  handlers:
    - name: 重启Nginx服务
      service:
        name: nginx
        state: restarted
        enabled: yes