---
- name: 安全配置Nginx服务
  hosts: all
  become: yes
  vars:
    nginx_port: 10080
    nginx_conf: "/etc/nginx/conf.d/default.conf"
  
  tasks:
    - name: 安装必要工具
      yum:
        name: [epel-release, yum-utils, patch]
        state: present

    - name: 添加Nginx官方源
      yum_repository:
        name: nginx-stable
        description: Nginx Stable Repo
        baseurl: https://nginx.org/packages/centos/7/$basearch/
        gpgcheck: yes
        gpgkey: https://nginx.org/keys/nginx_signing.key
        enabled: yes

    - name: 安装Nginx
      yum:
        name: nginx
        state: present
        enablerepo: nginx-stable,epel

    - name: 生成配置补丁文件
      copy:
        content: |
          --- default.conf.bak
          +++ default.conf
          @@ -2,7 +2,7 @@
           server {
           -    listen       80;
           +    listen       {{ nginx_port }};
                server_name  localhost;
        dest: /tmp/nginx_port.patch
        mode: 0644

    - name: 应用配置补丁
      patch:
        src: /tmp/nginx_port.patch
        dest: "{{ nginx_conf }}"
        backup: yes
        validate: "/usr/sbin/nginx -t -c %s"
      notify:
        - 安全重启服务

    - name: 最终配置验证
      command: nginx -t
      changed_when: false
      register: config_test
      failed_when: config_test.rc != 0

  handlers:
    - name: 安全重启服务
      service:
        name: nginx
        state: restarted
        enabled: yes
      async: 120
      poll: 5