---
- name: 安装Nginx
  hosts: all
  become: yes
  vars:
    target_port: 10080
    nginx_conf: "/etc/nginx/conf.d/default.conf"

  tasks:
    # 安装Nginx
    - name: 安装EPEL仓库
      yum:
        name: epel-release
        state: present

    - name: 安装Nginx
      yum:
        name: nginx
        state: present
      notify: 重启Nginx

    # 配置管理
    - name: 创建配置备份
      copy:
        src: "{{ nginx_conf }}"
        dest: "{{ nginx_conf }}.bak"
        remote_src: yes

    - name: 修改监听端口
      lineinfile:
        path: "{{ nginx_conf }}"
        regexp: '^listen\s+(80)(\s|;|$)'
        line: 'listen {{ target_port }}\2'
        backrefs: yes
      notify:
        - 重启Nginx
        - 验证配置语法

    # 验证配置
    - name: 验证配置语法
      command: nginx -t
      changed_when: false
      listen: 验证配置语法

    # 服务管理
    - name: 检查Nginx状态
      service:
        name: nginx
        state: restarted
      when: sed_result.changed

  handlers:
    - name: 重启Nginx
      service:
        name: nginx
        state: restarted

    - name: 验证配置语法
      command: nginx -t
      changed_when: false
      listen: 验证配置语法