---
- name: 使用sed安全修改Nginx端口
  hosts: all
  become: yes
  vars:
    target_port: 10080
    nginx_conf: "/etc/nginx/conf.d/default.conf"

  tasks:
    # 安装Nginx
    - name: 安装EPEL仓库
      yum:
        name: epel-release
        state: present

    - name: 安装Nginx
      yum:
        name: nginx
        state: present
      notify: 重启Nginx

    # 配置管理
    - name: 创建配置备份
      copy:
        src: "{{ nginx_conf }}"
        dest: "{{ nginx_conf }}.bak"
        remote_src: yes

    - name: 精确修改监听端口
	    shell: |
        sed -i 's/\\(listen\\s*\\)80;/\\110080;/'  "{{ nginx_conf }}"
      args:
        warn: no
      register: sed_result
      changed_when: "'已修改' in sed_result.stdout"
      check_mode: no

    # 验证配置
    - name: 检查配置语法
      command: nginx -t
      register: nginx_check
      changed_when: false
      failed_when: nginx_check.rc != 0

    - name: 验证端口修改
      lineinfile:
        path: "{{ nginx_conf }}"
        regexp: '^ {4}listen {{ target_port }};'
        state: present
      check_mode: yes
      changed_when: false

    # 服务管理
    - name: 检查Nginx状态
      service:
        name: nginx
        state: restarted
      when: sed_result.changed

  handlers:
    - name: 重启Nginx
      service:
        name: nginx
        state: restarted