---
- name: Get SSH Server Version
  hosts: all
  become: yes
  tasks:
    - name: Get SSHd version via command (Linux/Unix)
      ansible.builtin.shell:
        cmd: "sshd -V 2>&1 | grep -Eo '[0-9]+\\.[0-9]+(p[0-9]+)?' | head -1"
      register: sshd_version
      ignore_errors: yes
      when: ansible_facts['os_family'] != 'Windows'

    - name: Get OpenSSH version via package manager (RedHat)
      ansible.builtin.yum:
        list: openssh-server
      register: openssh_pkg
      when: 
        - ansible_facts['os_family'] == 'RedHat'
        - sshd_version is failed

    - name: Get OpenSSH version via package manager (Debian)
      ansible.builtin.apt:
        list: openssh-server
      register: openssh_pkg
      when: 
        - ansible_facts['os_family'] == 'Debian'
        - sshd_version is failed

    - name: Show SSH Server Version
      ansible.builtin.debug:
        msg: 
          - "SSH Server Version: {{ sshd_version.stdout | default('Not available') }}"
          - "OpenSSH Package Info: {{ openssh_pkg.stdout | default('Not available') }}"