---
- name: 系统信息实时检查Playbook
  hosts: all
  become: yes
  vars:
    COLOR_HEADER: "\\033[1;35m"   # 品红
    COLOR_TITLE: "\\033[1;36m"    # 青色
    COLOR_INFO: "\\033[1;32m"     # 绿色
    COLOR_RESET: "\\033[0m"

  tasks:
    - name: 显示系统基本信息
      ansible.builtin.command:
        cmd: |
          echo -e "\n{{ COLOR_HEADER }}==============================================================={{ COLOR_RESET}"
          echo -e "{{ COLOR_TITLE }}系统基本信息:{{ COLOR_RESET}"
          echo -e "{{ COLOR_INFO }}主机名        : {{ ansible_hostname }}"
          echo -e "操作系统      : {{ ansible_distribution }} {{ ansible_distribution_version }}"
          echo -e "内核版本      : {{ ansible_kernel }}"
          echo -e "运行时间      : {{ (ansible_uptime_seconds|int)/3600 | round(2) }} 小时"
          echo -e "SELinux状态  : {{ ansible_selinux.status|upper }}{{ COLOR_RESET}"
          echo -e "{{ COLOR_HEADER }}==============================================================={{ COLOR_RESET}\n"
      changed_when: false

    - name: 显示CPU信息
      ansible.builtin.command:
        cmd: |
          echo -e "{{ COLOR_TITLE }}CPU信息:{{ COLOR_RESET}"
          echo -e "{{ COLOR_INFO }}逻辑核心数 : {{ ansible_processor_vcpus }}"
          echo -e "物理核心数 : {{ ansible_processor_cores }}"
          echo -e "CPU型号    : {{ ansible_processor[2] | default('未知') }}{{ COLOR_RESET}"
          echo -e "{{ COLOR_HEADER }}---------------------------------------------------------------{{ COLOR_RESET}\n"
      changed_when: false

    - name: 显示内存信息
      ansible.builtin.command:
        cmd: |
          echo -e "{{ COLOR_TITLE }}内存信息:{{ COLOR_RESET}"
          echo -e "{{ COLOR_INFO }}总内存      : {{ (ansible_memtotal_mb / 1024) | round(2) }} GB"
          echo -e "可用内存    : {{ (ansible_memfree_mb / 1024) | round(2) }} GB"
          echo -e "使用率      : {{ (100 - (ansible_memfree_mb / ansible_memtotal_mb * 100)) | round(2) }}%{{ COLOR_RESET}"
          echo -e "{{ COLOR_HEADER }}---------------------------------------------------------------{{ COLOR_RESET}\n"
      changed_when: false

    - name: 显示磁盘信息
      ansible.builtin.command:
        cmd: |
          echo -e "{{ COLOR_TITLE }}磁盘使用情况:{{ COLOR_RESET}"
          df -hTP --exclude-type=tmpfs | awk -v color="${COLOR_INFO}" -v reset="${COLOR_RESET}" \
          'NR==1 {print color $0 reset} NR>1 {print $0}'
          echo -e "\n{{ COLOR_HEADER }}---------------------------------------------------------------{{ COLOR_RESET}\n"
      changed_when: false

    - name: 显示网络信息
      ansible.builtin.command:
        cmd: |
          echo -e "{{ COLOR_TITLE }}网络信息:{{ COLOR_RESET}"
          echo -e "{{ COLOR_INFO }}私有IP      : {{ ansible_default_ipv4.address }}"
          echo -e "网关地址    : {{ ansible_default_ipv4.gateway }}"
          echo -e "MAC地址     : {{ ansible_default_ipv4.macaddress }}{{ COLOR_RESET}"
          echo -e "{{ COLOR_HEADER }}==============================================================={{ COLOR_RESET}\n"
      changed_when: false