---
- name: 系统信息实时检查Playbook
  hosts: all
  become: yes
  vars:
    COLOR_HEADER: "\033[1;35m"   # 品红
    COLOR_TITLE: "\033[1;36m"    # 青色
    COLOR_INFO: "\033[1;32m"     # 绿色
    COLOR_WARN: "\033[1;33m"     # 黄色
    COLOR_RESET: "\033[0m"

  tasks:
    - name: 收集系统基础信息
      ansible.builtin.setup:
        filter: "*"
      register: sys_info

    - name: 显示系统基本信息
      ansible.builtin.debug:
        msg: |
          {{ COLOR_HEADER }}================================================================{{ COLOR_RESET }}
          {{ COLOR_TITLE }}系统基本信息:{{ COLOR_RESET }}
          {{ COLOR_INFO }}主机名        : {{ ansible_hostname }}
          操作系统      : {{ ansible_distribution }} {{ ansible_distribution_version }} 
          内核版本      : {{ ansible_kernel }}
          运行时间      : {{ (ansible_uptime_seconds|int)/3600 }} 小时
          SELinux状态  : {{ ansible_selinux.status|upper }}
          {{ COLOR_HEADER }}================================================================{{ COLOR_RESET }}

    - name: 获取CPU信息
      block:
        - name: 提取CPU信息
          ansible.builtin.shell: |
            grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ *//'
          register: cpu_model
          changed_when: false

        - name: 显示CPU信息
          ansible.builtin.debug:
            msg: |
              {{ COLOR_TITLE }}CPU信息:{{ COLOR_RESET }}
              {{ COLOR_INFO }}逻辑核心数 : {{ ansible_processor_vcpus }}
              物理核心数 : {{ ansible_processor_cores }}
              CPU型号    : {{ cpu_model.stdout | trim }}
              {{ COLOR_HEADER }}-----------------------------------------------{{ COLOR_RESET }}
      rescue:
        - name: 显示CPU信息错误
          ansible.builtin.debug:
            msg: "{{ COLOR_WARN}}无法获取CPU详细信息{{ COLOR_RESET }}"

    - name: 获取内存信息
      ansible.builtin.debug:
        msg: |
          {{ COLOR_TITLE }}内存信息:{{ COLOR_RESET }}
          {{ COLOR_INFO }}总内存      : {{ (ansible_memtotal_mb / 1024)|round(2) }} GB
          可用内存    : {{ (ansible_memfree_mb / 1024)|round(2) }} GB
          使用率      : {{ (100 - (ansible_memfree_mb / ansible_memtotal_mb * 100)) | round(2) }}%
          {{ COLOR_HEADER }}-----------------------------------------------{{ COLOR_RESET }}

    - name: 获取磁盘信息
      ansible.builtin.command: df -hTP --exclude-type=tmpfs
      register: disks
      changed_when: false

    - name: 显示磁盘信息
      ansible.builtin.debug:
        msg: |
          {{ COLOR_TITLE }}磁盘使用情况:{{ COLOR_RESET }}
          {{ COLOR_INFO }}{{ disks.stdout | trim | replace('\n', '\n          ') }}
          {{ COLOR_HEADER }}-----------------------------------------------{{ COLOR_RESET }}

    - name: 获取网络信息
      block:
        - name: 尝试获取公网IP
          ansible.builtin.uri:
            url: https://ifconfig.me/ip
            return_content: yes
            timeout: 2
          register: public_ip
          ignore_errors: yes

        - name: 显示网络信息
          ansible.builtin.debug:
            msg: |
              {{ COLOR_TITLE }}网络信息:{{ COLOR_RESET }}
              {{ COLOR_INFO }}私有IP      : {{ ansible_default_ipv4.address }}
              网关地址    : {{ ansible_default_ipv4.gateway }}
              MAC地址     : {{ ansible_default_ipv4.macaddress }}
              公网IP      : {{ (public_ip.content | default(COLOR_WARN~'N/A'~COLOR_RESET)) | trim }}
              {{ COLOR_HEADER }}================================================================{{ COLOR_RESET }}
      rescue:
        - name: 显示网络错误
          ansible.builtin.debug:
            msg: "{{ COLOR_WARN}}公网IP检测失败，请检查网络连接{{ COLOR_RESET }}"

    - name: 显示实时进程信息
      block:
        - name: 获取进程TOP10
          ansible.builtin.shell: |
            ps -eo pid,user,%cpu,%mem,command --sort=-%cpu | head -n 6
            echo; 
            ps -eo pid,user,%cpu,%mem,command --sort=-%mem | head -n 6
          register: top_procs
          changed_when: false

        - name: 显示进程信息
          ansible.builtin.debug:
            msg: |
              {{ COLOR_TITLE }}资源占用TOP5:{{ COLOR_RESET }}
              {{ COLOR_INFO }}CPU排行:
              {{ top_procs.stdout_lines[0:6] | join('\n') }}

              {{ COLOR_INFO }}内存排行:
              {{ top_procs.stdout_lines[7:13] | join('\n') }}
              {{ COLOR_HEADER }}================================================================{{ COLOR_RESET }}