---
- name: 系统信息检查Playbook
  hosts: all
  become: yes
  vars:
    report_path: "/tmp/system_report.log"
  
  tasks:
    - name: 清理旧报告文件
      ansible.builtin.file:
        path: "{{ report_path }}"
        state: absent

    - name: 收集系统基本信息
      ansible.builtin.setup:
        filter: 
          - "ansible_distribution*"
          - "ansible_kernel"
          - "ansible_hostname"
          - "ansible_selinux"
          - "ansible_userspace_*"
          - "ansible_date_time"
      register: sys_info

    - name: 获取CPU信息
      ansible.builtin.shell:
        cmd: |
          Physical_CPUs=$(grep "physical id" /proc/cpuinfo | sort | uniq | wc -l)
          Virt_CPUs=$(grep "processor" /proc/cpuinfo | wc -l)
          CPU_Kernels=$(grep "cores" /proc/cpuinfo | uniq | awk -F ': ' '{print $2}')
          CPU_Type=$(grep "model name" /proc/cpuinfo | awk -F ': ' '{print $2}' | sort | uniq)
          echo "Physical_CPUs=${Physical_CPUs};Virt_CPUs=${Virt_CPUs};CPU_Kernels=${CPU_Kernels};CPU_Type='${CPU_Type}'"
      register: cpu_raw
      changed_when: false

    - name: 获取内存使用率
      ansible.builtin.shell:
        cmd: free -m | awk '/Mem/{printf "%.2f", $3/$2 * 100}'
      register: mem_usage
      changed_when: false

    - name: 获取磁盘信息
      ansible.builtin.shell:
        cmd: df -hTP --exclude-type=tmpfs
      register: disk_info
      changed_when: false

    - name: 获取公网IP
      ansible.builtin.uri:
        url: https://ifconfig.me/ip
        return_content: yes
      register: public_ip
      ignore_errors: yes

    - name: 生成完整检查报告
      ansible.builtin.template:
        src: full_report.j2
        dest: "{{ report_path }}"
      notify:
        - 显示完成消息

  handlers:
    - name: 显示完成消息
      ansible.builtin.debug:
        msg: "完整系统检查报告已生成至 {{ report_path }}"